server:
  port: 8081

spring:
  application:
    name: scrapper
  datasource:
    url: ${SCRAPPER_DB_URL:jdbc:postgresql://localhost:5432/link_tracker}
    username: ${SCRAPPER_DB_USERNAME:postgres}
    password: ${SCRAPPER_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/migrations/master.xml
    enabled: true

app:
  database:
    access-type: ${SCRAPPER_DB_ACCESS_TYPE:SQL}
  grpc:
    server:
      enabled: ${SCRAPPER_GRPC_SERVER_ENABLED:false}
      port: ${SCRAPPER_GRPC_PORT:8091}
  bot:
    base-url: ${BOT_BASE_URL:http://localhost:8080}
    transport: ${BOT_TRANSPORT:http}
    grpc:
      host: ${BOT_GRPC_HOST:localhost}
      port: ${BOT_GRPC_PORT:8090}
  scheduler:
    enabled: true
    interval: 60000
  stackoverflow:
    base-url: ${STACKOVERFLOW_BASE_URL:https://api.stackexchange.com}
    site: ${STACKOVERFLOW_SITE:stackoverflow}
    key: ${STACKOVERFLOW_KEY:} # Use env variable. DO NOT KEEP TOKEN HERE
    access-token: ${STACKOVERFLOW_ACCESS_TOKEN:} # Use env variable. DO NOT KEEP TOKEN HERE
  github:
    base-url: ${GITHUB_BASE_URL:https://api.github.com}
    token: ${GITHUB_TOKEN:} # Use env variable. DO NOT KEEP TOKEN HERE
