server:
  port: 8080

spring:
  application:
    name: bot

app:
  grpc:
    server:
      enabled: ${BOT_GRPC_SERVER_ENABLED:false}
      port: ${BOT_GRPC_PORT:8090}
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    max-send-attempts: 3
    delivery-retry-enabled: true
    delivery-retry-interval: 1m
    debug: false
    set-my-commands-enabled: true
  scrapper:
    base-url: ${SCRAPPER_BASE_URL:http://localhost:8081}
    transport: ${SCRAPPER_TRANSPORT:http}
    grpc:
      host: ${SCRAPPER_GRPC_HOST:localhost}
      port: ${SCRAPPER_GRPC_PORT:8091}
