// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

/**
 * Protobuf type {@code linktracker.grpc.AddLinkRequest}
 */
@com.google.protobuf.Generated
public final class AddLinkRequest extends com.google.protobuf.GeneratedMessage
        implements
        // @@protoc_insertion_point(message_implements:linktracker.grpc.AddLinkRequest)
        AddLinkRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 4,
                /* suffix= */ "",
                "AddLinkRequest");
    }
    // Use AddLinkRequest.newBuilder() to construct.
    private AddLinkRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private AddLinkRequest() {
        link_ = "";
        tags_ = com.google.protobuf.LazyStringArrayList.emptyList();
        filters_ = com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_AddLinkRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_AddLinkRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        backend.academy.linktracker.grpc.AddLinkRequest.class,
                        backend.academy.linktracker.grpc.AddLinkRequest.Builder.class);
    }

    public static final int CHAT_ID_FIELD_NUMBER = 1;
    private long chatId_ = 0L;
    /**
     * <code>int64 chat_id = 1;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
        return chatId_;
    }

    public static final int LINK_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private volatile java.lang.Object link_ = "";
    /**
     * <code>string link = 2;</code>
     * @return The link.
     */
    @java.lang.Override
    public java.lang.String getLink() {
        java.lang.Object ref = link_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            link_ = s;
            return s;
        }
    }
    /**
     * <code>string link = 2;</code>
     * @return The bytes for link.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLinkBytes() {
        java.lang.Object ref = link_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            link_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int TAGS_FIELD_NUMBER = 3;

    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList tags_ = com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string tags = 3;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList getTagsList() {
        return tags_;
    }
    /**
     * <code>repeated string tags = 3;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
        return tags_.size();
    }
    /**
     * <code>repeated string tags = 3;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
        return tags_.get(index);
    }
    /**
     * <code>repeated string tags = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString getTagsBytes(int index) {
        return tags_.getByteString(index);
    }

    public static final int FILTERS_FIELD_NUMBER = 4;

    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList filters_ = com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string filters = 4;</code>
     * @return A list containing the filters.
     */
    public com.google.protobuf.ProtocolStringList getFiltersList() {
        return filters_;
    }
    /**
     * <code>repeated string filters = 4;</code>
     * @return The count of filters.
     */
    public int getFiltersCount() {
        return filters_.size();
    }
    /**
     * <code>repeated string filters = 4;</code>
     * @param index The index of the element to return.
     * @return The filters at the given index.
     */
    public java.lang.String getFilters(int index) {
        return filters_.get(index);
    }
    /**
     * <code>repeated string filters = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the filters at the given index.
     */
    public com.google.protobuf.ByteString getFiltersBytes(int index) {
        return filters_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (chatId_ != 0L) {
            output.writeInt64(1, chatId_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(link_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 2, link_);
        }
        for (int i = 0; i < tags_.size(); i++) {
            com.google.protobuf.GeneratedMessage.writeString(output, 3, tags_.getRaw(i));
        }
        for (int i = 0; i < filters_.size(); i++) {
            com.google.protobuf.GeneratedMessage.writeString(output, 4, filters_.getRaw(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (chatId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, chatId_);
        }
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(link_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(2, link_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < tags_.size(); i++) {
                dataSize += computeStringSizeNoTag(tags_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getTagsList().size();
        }
        {
            int dataSize = 0;
            for (int i = 0; i < filters_.size(); i++) {
                dataSize += computeStringSizeNoTag(filters_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getFiltersList().size();
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof backend.academy.linktracker.grpc.AddLinkRequest)) {
            return super.equals(obj);
        }
        backend.academy.linktracker.grpc.AddLinkRequest other = (backend.academy.linktracker.grpc.AddLinkRequest) obj;

        if (getChatId() != other.getChatId()) return false;
        if (!getLink().equals(other.getLink())) return false;
        if (!getTagsList().equals(other.getTagsList())) return false;
        if (!getFiltersList().equals(other.getFiltersList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CHAT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getChatId());
        hash = (37 * hash) + LINK_FIELD_NUMBER;
        hash = (53 * hash) + getLink().hashCode();
        if (getTagsCount() > 0) {
            hash = (37 * hash) + TAGS_FIELD_NUMBER;
            hash = (53 * hash) + getTagsList().hashCode();
        }
        if (getFiltersCount() > 0) {
            hash = (37 * hash) + FILTERS_FIELD_NUMBER;
            hash = (53 * hash) + getFiltersList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(
            com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(
            byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest parseFrom(
            com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(backend.academy.linktracker.grpc.AddLinkRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code linktracker.grpc.AddLinkRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements
            // @@protoc_insertion_point(builder_implements:linktracker.grpc.AddLinkRequest)
            backend.academy.linktracker.grpc.AddLinkRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_AddLinkRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_AddLinkRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            backend.academy.linktracker.grpc.AddLinkRequest.class,
                            backend.academy.linktracker.grpc.AddLinkRequest.Builder.class);
        }

        // Construct using backend.academy.linktracker.grpc.AddLinkRequest.newBuilder()
        private Builder() {}

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            chatId_ = 0L;
            link_ = "";
            tags_ = com.google.protobuf.LazyStringArrayList.emptyList();
            filters_ = com.google.protobuf.LazyStringArrayList.emptyList();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_AddLinkRequest_descriptor;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.AddLinkRequest getDefaultInstanceForType() {
            return backend.academy.linktracker.grpc.AddLinkRequest.getDefaultInstance();
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.AddLinkRequest build() {
            backend.academy.linktracker.grpc.AddLinkRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.AddLinkRequest buildPartial() {
            backend.academy.linktracker.grpc.AddLinkRequest result =
                    new backend.academy.linktracker.grpc.AddLinkRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(backend.academy.linktracker.grpc.AddLinkRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.chatId_ = chatId_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.link_ = link_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                tags_.makeImmutable();
                result.tags_ = tags_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                filters_.makeImmutable();
                result.filters_ = filters_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof backend.academy.linktracker.grpc.AddLinkRequest) {
                return mergeFrom((backend.academy.linktracker.grpc.AddLinkRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(backend.academy.linktracker.grpc.AddLinkRequest other) {
            if (other == backend.academy.linktracker.grpc.AddLinkRequest.getDefaultInstance()) return this;
            if (other.getChatId() != 0L) {
                setChatId(other.getChatId());
            }
            if (!other.getLink().isEmpty()) {
                link_ = other.link_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.tags_.isEmpty()) {
                if (tags_.isEmpty()) {
                    tags_ = other.tags_;
                    bitField0_ |= 0x00000004;
                } else {
                    ensureTagsIsMutable();
                    tags_.addAll(other.tags_);
                }
                onChanged();
            }
            if (!other.filters_.isEmpty()) {
                if (filters_.isEmpty()) {
                    filters_ = other.filters_;
                    bitField0_ |= 0x00000008;
                } else {
                    ensureFiltersIsMutable();
                    filters_.addAll(other.filters_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            chatId_ = input.readInt64();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        case 18: {
                            link_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();
                            ensureTagsIsMutable();
                            tags_.add(s);
                            break;
                        } // case 26
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();
                            ensureFiltersIsMutable();
                            filters_.add(s);
                            break;
                        } // case 34
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private long chatId_;
        /**
         * <code>int64 chat_id = 1;</code>
         * @return The chatId.
         */
        @java.lang.Override
        public long getChatId() {
            return chatId_;
        }
        /**
         * <code>int64 chat_id = 1;</code>
         * @param value The chatId to set.
         * @return This builder for chaining.
         */
        public Builder setChatId(long value) {

            chatId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <code>int64 chat_id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearChatId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            chatId_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object link_ = "";
        /**
         * <code>string link = 2;</code>
         * @return The link.
         */
        public java.lang.String getLink() {
            java.lang.Object ref = link_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                link_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string link = 2;</code>
         * @return The bytes for link.
         */
        public com.google.protobuf.ByteString getLinkBytes() {
            java.lang.Object ref = link_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                link_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string link = 2;</code>
         * @param value The link to set.
         * @return This builder for chaining.
         */
        public Builder setLink(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            link_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>string link = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLink() {
            link_ = getDefaultInstance().getLink();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }
        /**
         * <code>string link = 2;</code>
         * @param value The bytes for link to set.
         * @return This builder for chaining.
         */
        public Builder setLinkBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            link_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private com.google.protobuf.LazyStringArrayList tags_ = com.google.protobuf.LazyStringArrayList.emptyList();

        private void ensureTagsIsMutable() {
            if (!tags_.isModifiable()) {
                tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
            }
            bitField0_ |= 0x00000004;
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @return A list containing the tags.
         */
        public com.google.protobuf.ProtocolStringList getTagsList() {
            tags_.makeImmutable();
            return tags_;
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @return The count of tags.
         */
        public int getTagsCount() {
            return tags_.size();
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @param index The index of the element to return.
         * @return The tags at the given index.
         */
        public java.lang.String getTags(int index) {
            return tags_.get(index);
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @param index The index of the value to return.
         * @return The bytes of the tags at the given index.
         */
        public com.google.protobuf.ByteString getTagsBytes(int index) {
            return tags_.getByteString(index);
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @param index The index to set the value at.
         * @param value The tags to set.
         * @return This builder for chaining.
         */
        public Builder setTags(int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureTagsIsMutable();
            tags_.set(index, value);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @param value The tags to add.
         * @return This builder for chaining.
         */
        public Builder addTags(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureTagsIsMutable();
            tags_.add(value);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @param values The tags to add.
         * @return This builder for chaining.
         */
        public Builder addAllTags(java.lang.Iterable<java.lang.String> values) {
            ensureTagsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, tags_);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearTags() {
            tags_ = com.google.protobuf.LazyStringArrayList.emptyList();
            bitField0_ = (bitField0_ & ~0x00000004);
            ;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string tags = 3;</code>
         * @param value The bytes of the tags to add.
         * @return This builder for chaining.
         */
        public Builder addTagsBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureTagsIsMutable();
            tags_.add(value);
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        private com.google.protobuf.LazyStringArrayList filters_ = com.google.protobuf.LazyStringArrayList.emptyList();

        private void ensureFiltersIsMutable() {
            if (!filters_.isModifiable()) {
                filters_ = new com.google.protobuf.LazyStringArrayList(filters_);
            }
            bitField0_ |= 0x00000008;
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @return A list containing the filters.
         */
        public com.google.protobuf.ProtocolStringList getFiltersList() {
            filters_.makeImmutable();
            return filters_;
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @return The count of filters.
         */
        public int getFiltersCount() {
            return filters_.size();
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @param index The index of the element to return.
         * @return The filters at the given index.
         */
        public java.lang.String getFilters(int index) {
            return filters_.get(index);
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @param index The index of the value to return.
         * @return The bytes of the filters at the given index.
         */
        public com.google.protobuf.ByteString getFiltersBytes(int index) {
            return filters_.getByteString(index);
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @param index The index to set the value at.
         * @param value The filters to set.
         * @return This builder for chaining.
         */
        public Builder setFilters(int index, java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureFiltersIsMutable();
            filters_.set(index, value);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @param value The filters to add.
         * @return This builder for chaining.
         */
        public Builder addFilters(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureFiltersIsMutable();
            filters_.add(value);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @param values The filters to add.
         * @return This builder for chaining.
         */
        public Builder addAllFilters(java.lang.Iterable<java.lang.String> values) {
            ensureFiltersIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, filters_);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearFilters() {
            filters_ = com.google.protobuf.LazyStringArrayList.emptyList();
            bitField0_ = (bitField0_ & ~0x00000008);
            ;
            onChanged();
            return this;
        }
        /**
         * <code>repeated string filters = 4;</code>
         * @param value The bytes of the filters to add.
         * @return This builder for chaining.
         */
        public Builder addFiltersBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureFiltersIsMutable();
            filters_.add(value);
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:linktracker.grpc.AddLinkRequest)
    }

    // @@protoc_insertion_point(class_scope:linktracker.grpc.AddLinkRequest)
    private static final backend.academy.linktracker.grpc.AddLinkRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new backend.academy.linktracker.grpc.AddLinkRequest();
    }

    public static backend.academy.linktracker.grpc.AddLinkRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddLinkRequest> PARSER =
            new com.google.protobuf.AbstractParser<AddLinkRequest>() {
                @java.lang.Override
                public AddLinkRequest parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

    public static com.google.protobuf.Parser<AddLinkRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddLinkRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public backend.academy.linktracker.grpc.AddLinkRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
