// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

@com.google.protobuf.Generated
public interface LinkResponseOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:linktracker.grpc.LinkResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string url = 2;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 2;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString getUrlBytes();

    /**
     * <code>repeated string tags = 3;</code>
     * @return A list containing the tags.
     */
    java.util.List<java.lang.String> getTagsList();
    /**
     * <code>repeated string tags = 3;</code>
     * @return The count of tags.
     */
    int getTagsCount();
    /**
     * <code>repeated string tags = 3;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    java.lang.String getTags(int index);
    /**
     * <code>repeated string tags = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    com.google.protobuf.ByteString getTagsBytes(int index);

    /**
     * <code>repeated string filters = 4;</code>
     * @return A list containing the filters.
     */
    java.util.List<java.lang.String> getFiltersList();
    /**
     * <code>repeated string filters = 4;</code>
     * @return The count of filters.
     */
    int getFiltersCount();
    /**
     * <code>repeated string filters = 4;</code>
     * @param index The index of the element to return.
     * @return The filters at the given index.
     */
    java.lang.String getFilters(int index);
    /**
     * <code>repeated string filters = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the filters at the given index.
     */
    com.google.protobuf.ByteString getFiltersBytes(int index);
}
