// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

@com.google.protobuf.Generated
public interface ListLinksResponseOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:linktracker.grpc.ListLinksResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    java.util.List<backend.academy.linktracker.grpc.LinkResponse> getLinksList();
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    backend.academy.linktracker.grpc.LinkResponse getLinks(int index);
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    int getLinksCount();
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    java.util.List<? extends backend.academy.linktracker.grpc.LinkResponseOrBuilder> getLinksOrBuilderList();
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    backend.academy.linktracker.grpc.LinkResponseOrBuilder getLinksOrBuilder(int index);

    /**
     * <code>int32 size = 2;</code>
     * @return The size.
     */
    int getSize();
}
