// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

/**
 * Protobuf type {@code linktracker.grpc.ProcessingFailureReportRequest}
 */
@com.google.protobuf.Generated
public final class ProcessingFailureReportRequest extends com.google.protobuf.GeneratedMessage
        implements
        // @@protoc_insertion_point(message_implements:linktracker.grpc.ProcessingFailureReportRequest)
        ProcessingFailureReportRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 4,
                /* suffix= */ "",
                "ProcessingFailureReportRequest");
    }
    // Use ProcessingFailureReportRequest.newBuilder() to construct.
    private ProcessingFailureReportRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ProcessingFailureReportRequest() {
        description_ = "";
        tgChatIds_ = emptyLongList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_ProcessingFailureReportRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_ProcessingFailureReportRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        backend.academy.linktracker.grpc.ProcessingFailureReportRequest.class,
                        backend.academy.linktracker.grpc.ProcessingFailureReportRequest.Builder.class);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 1;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            description_ = s;
            return s;
        }
    }
    /**
     * <code>string description = 1;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            description_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int TG_CHAT_IDS_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList tgChatIds_ = emptyLongList();
    /**
     * <code>repeated int64 tg_chat_ids = 2;</code>
     * @return A list containing the tgChatIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long> getTgChatIdsList() {
        return tgChatIds_;
    }
    /**
     * <code>repeated int64 tg_chat_ids = 2;</code>
     * @return The count of tgChatIds.
     */
    public int getTgChatIdsCount() {
        return tgChatIds_.size();
    }
    /**
     * <code>repeated int64 tg_chat_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The tgChatIds at the given index.
     */
    public long getTgChatIds(int index) {
        return tgChatIds_.getLong(index);
    }

    private int tgChatIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        getSerializedSize();
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, description_);
        }
        if (getTgChatIdsList().size() > 0) {
            output.writeUInt32NoTag(18);
            output.writeUInt32NoTag(tgChatIdsMemoizedSerializedSize);
        }
        for (int i = 0; i < tgChatIds_.size(); i++) {
            output.writeInt64NoTag(tgChatIds_.getLong(i));
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, description_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < tgChatIds_.size(); i++) {
                dataSize += com.google.protobuf.CodedOutputStream.computeInt64SizeNoTag(tgChatIds_.getLong(i));
            }
            size += dataSize;
            if (!getTgChatIdsList().isEmpty()) {
                size += 1;
                size += com.google.protobuf.CodedOutputStream.computeInt32SizeNoTag(dataSize);
            }
            tgChatIdsMemoizedSerializedSize = dataSize;
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof backend.academy.linktracker.grpc.ProcessingFailureReportRequest)) {
            return super.equals(obj);
        }
        backend.academy.linktracker.grpc.ProcessingFailureReportRequest other =
                (backend.academy.linktracker.grpc.ProcessingFailureReportRequest) obj;

        if (!getDescription().equals(other.getDescription())) return false;
        if (!getTgChatIdsList().equals(other.getTgChatIdsList())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
        if (getTgChatIdsCount() > 0) {
            hash = (37 * hash) + TG_CHAT_IDS_FIELD_NUMBER;
            hash = (53 * hash) + getTgChatIdsList().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(
            com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(
            com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(
            byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseDelimitedFrom(
            java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(
            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest parseFrom(
            com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(backend.academy.linktracker.grpc.ProcessingFailureReportRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code linktracker.grpc.ProcessingFailureReportRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements
            // @@protoc_insertion_point(builder_implements:linktracker.grpc.ProcessingFailureReportRequest)
            backend.academy.linktracker.grpc.ProcessingFailureReportRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_ProcessingFailureReportRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_ProcessingFailureReportRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            backend.academy.linktracker.grpc.ProcessingFailureReportRequest.class,
                            backend.academy.linktracker.grpc.ProcessingFailureReportRequest.Builder.class);
        }

        // Construct using backend.academy.linktracker.grpc.ProcessingFailureReportRequest.newBuilder()
        private Builder() {}

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            description_ = "";
            tgChatIds_ = emptyLongList();
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_ProcessingFailureReportRequest_descriptor;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.ProcessingFailureReportRequest getDefaultInstanceForType() {
            return backend.academy.linktracker.grpc.ProcessingFailureReportRequest.getDefaultInstance();
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.ProcessingFailureReportRequest build() {
            backend.academy.linktracker.grpc.ProcessingFailureReportRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.ProcessingFailureReportRequest buildPartial() {
            backend.academy.linktracker.grpc.ProcessingFailureReportRequest result =
                    new backend.academy.linktracker.grpc.ProcessingFailureReportRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(backend.academy.linktracker.grpc.ProcessingFailureReportRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.description_ = description_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                tgChatIds_.makeImmutable();
                result.tgChatIds_ = tgChatIds_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof backend.academy.linktracker.grpc.ProcessingFailureReportRequest) {
                return mergeFrom((backend.academy.linktracker.grpc.ProcessingFailureReportRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(backend.academy.linktracker.grpc.ProcessingFailureReportRequest other) {
            if (other == backend.academy.linktracker.grpc.ProcessingFailureReportRequest.getDefaultInstance())
                return this;
            if (!other.getDescription().isEmpty()) {
                description_ = other.description_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (!other.tgChatIds_.isEmpty()) {
                if (tgChatIds_.isEmpty()) {
                    tgChatIds_ = other.tgChatIds_;
                    tgChatIds_.makeImmutable();
                    bitField0_ |= 0x00000002;
                } else {
                    ensureTgChatIdsIsMutable();
                    tgChatIds_.addAll(other.tgChatIds_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            description_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 16: {
                            long v = input.readInt64();
                            ensureTgChatIdsIsMutable();
                            tgChatIds_.addLong(v);
                            break;
                        } // case 16
                        case 18: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            ensureTgChatIdsIsMutable();
                            while (input.getBytesUntilLimit() > 0) {
                                tgChatIds_.addLong(input.readInt64());
                            }
                            input.popLimit(limit);
                            break;
                        } // case 18
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object description_ = "";
        /**
         * <code>string description = 1;</code>
         * @return The description.
         */
        public java.lang.String getDescription() {
            java.lang.Object ref = description_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                description_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }
        /**
         * <code>string description = 1;</code>
         * @return The bytes for description.
         */
        public com.google.protobuf.ByteString getDescriptionBytes() {
            java.lang.Object ref = description_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }
        /**
         * <code>string description = 1;</code>
         * @param value The description to set.
         * @return This builder for chaining.
         */
        public Builder setDescription(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            description_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <code>string description = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearDescription() {
            description_ = getDefaultInstance().getDescription();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }
        /**
         * <code>string description = 1;</code>
         * @param value The bytes for description to set.
         * @return This builder for chaining.
         */
        public Builder setDescriptionBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            description_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private com.google.protobuf.Internal.LongList tgChatIds_ = emptyLongList();

        private void ensureTgChatIdsIsMutable() {
            if (!tgChatIds_.isModifiable()) {
                tgChatIds_ = makeMutableCopy(tgChatIds_);
            }
            bitField0_ |= 0x00000002;
        }
        /**
         * <code>repeated int64 tg_chat_ids = 2;</code>
         * @return A list containing the tgChatIds.
         */
        public java.util.List<java.lang.Long> getTgChatIdsList() {
            tgChatIds_.makeImmutable();
            return tgChatIds_;
        }
        /**
         * <code>repeated int64 tg_chat_ids = 2;</code>
         * @return The count of tgChatIds.
         */
        public int getTgChatIdsCount() {
            return tgChatIds_.size();
        }
        /**
         * <code>repeated int64 tg_chat_ids = 2;</code>
         * @param index The index of the element to return.
         * @return The tgChatIds at the given index.
         */
        public long getTgChatIds(int index) {
            return tgChatIds_.getLong(index);
        }
        /**
         * <code>repeated int64 tg_chat_ids = 2;</code>
         * @param index The index to set the value at.
         * @param value The tgChatIds to set.
         * @return This builder for chaining.
         */
        public Builder setTgChatIds(int index, long value) {

            ensureTgChatIdsIsMutable();
            tgChatIds_.setLong(index, value);
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>repeated int64 tg_chat_ids = 2;</code>
         * @param value The tgChatIds to add.
         * @return This builder for chaining.
         */
        public Builder addTgChatIds(long value) {

            ensureTgChatIdsIsMutable();
            tgChatIds_.addLong(value);
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>repeated int64 tg_chat_ids = 2;</code>
         * @param values The tgChatIds to add.
         * @return This builder for chaining.
         */
        public Builder addAllTgChatIds(java.lang.Iterable<? extends java.lang.Long> values) {
            ensureTgChatIdsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(values, tgChatIds_);
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>repeated int64 tg_chat_ids = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearTgChatIds() {
            tgChatIds_ = emptyLongList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:linktracker.grpc.ProcessingFailureReportRequest)
    }

    // @@protoc_insertion_point(class_scope:linktracker.grpc.ProcessingFailureReportRequest)
    private static final backend.academy.linktracker.grpc.ProcessingFailureReportRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new backend.academy.linktracker.grpc.ProcessingFailureReportRequest();
    }

    public static backend.academy.linktracker.grpc.ProcessingFailureReportRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProcessingFailureReportRequest> PARSER =
            new com.google.protobuf.AbstractParser<ProcessingFailureReportRequest>() {
                @java.lang.Override
                public ProcessingFailureReportRequest parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

    public static com.google.protobuf.Parser<ProcessingFailureReportRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessingFailureReportRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public backend.academy.linktracker.grpc.ProcessingFailureReportRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
