// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

@com.google.protobuf.Generated
public interface RemoveLinkRequestOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:linktracker.grpc.RemoveLinkRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 chat_id = 1;</code>
     * @return The chatId.
     */
    long getChatId();

    /**
     * <code>string link = 2;</code>
     * @return The link.
     */
    java.lang.String getLink();
    /**
     * <code>string link = 2;</code>
     * @return The bytes for link.
     */
    com.google.protobuf.ByteString getLinkBytes();
}
