// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

@com.google.protobuf.Generated
public final class LinkTrackerProto extends com.google.protobuf.GeneratedFile {
    private LinkTrackerProto() {}

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 4,
                /* suffix= */ "",
                "LinkTrackerProto");
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_linktracker_grpc_Empty_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_Empty_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_linktracker_grpc_RegisterChatRequest_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_RegisterChatRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_linktracker_grpc_DeleteChatRequest_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_DeleteChatRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_linktracker_grpc_ListLinksRequest_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_ListLinksRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_linktracker_grpc_AddLinkRequest_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_AddLinkRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_linktracker_grpc_RemoveLinkRequest_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_RemoveLinkRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_linktracker_grpc_LinkResponse_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_LinkResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_linktracker_grpc_ListLinksResponse_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_ListLinksResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_linktracker_grpc_LinkUpdateRequest_descriptor;
    static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_linktracker_grpc_LinkUpdateRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\022link_tracker.proto\022\020linktracker.grpc\"\007"
                    + "\n\005Empty\"&\n\023RegisterChatRequest\022\017\n\007chat_i"
                    + "d\030\001 \001(\003\"$\n\021DeleteChatRequest\022\017\n\007chat_id\030"
                    + "\001 \001(\003\"#\n\020ListLinksRequest\022\017\n\007chat_id\030\001 \001"
                    + "(\003\"N\n\016AddLinkRequest\022\017\n\007chat_id\030\001 \001(\003\022\014\n"
                    + "\004link\030\002 \001(\t\022\014\n\004tags\030\003 \003(\t\022\017\n\007filters\030\004 \003"
                    + "(\t\"2\n\021RemoveLinkRequest\022\017\n\007chat_id\030\001 \001(\003"
                    + "\022\014\n\004link\030\002 \001(\t\"F\n\014LinkResponse\022\n\n\002id\030\001 \001"
                    + "(\003\022\013\n\003url\030\002 \001(\t\022\014\n\004tags\030\003 \003(\t\022\017\n\007filters"
                    + "\030\004 \003(\t\"P\n\021ListLinksResponse\022-\n\005links\030\001 \003"
                    + "(\0132\036.linktracker.grpc.LinkResponse\022\014\n\004si"
                    + "ze\030\002 \001(\005\"V\n\021LinkUpdateRequest\022\n\n\002id\030\001 \001("
                    + "\003\022\013\n\003url\030\002 \001(\t\022\023\n\013description\030\003 \001(\t\022\023\n\013t"
                    + "g_chat_ids\030\004 \003(\0032\243\003\n\017ScrapperService\022N\n\014"
                    + "RegisterChat\022%.linktracker.grpc.Register"
                    + "ChatRequest\032\027.linktracker.grpc.Empty\022J\n\n"
                    + "DeleteChat\022#.linktracker.grpc.DeleteChat"
                    + "Request\032\027.linktracker.grpc.Empty\022T\n\tList"
                    + "Links\022\".linktracker.grpc.ListLinksReques"
                    + "t\032#.linktracker.grpc.ListLinksResponse\022K"
                    + "\n\007AddLink\022 .linktracker.grpc.AddLinkRequ"
                    + "est\032\036.linktracker.grpc.LinkResponse\022Q\n\nR"
                    + "emoveLink\022#.linktracker.grpc.RemoveLinkR"
                    + "equest\032\036.linktracker.grpc.LinkResponse2b"
                    + "\n\021BotUpdatesService\022M\n\rProcessUpdate\022#.l"
                    + "inktracker.grpc.LinkUpdateRequest\032\027.link"
                    + "tracker.grpc.EmptyB6\n backend.academy.li"
                    + "nktracker.grpcB\020LinkTrackerProtoP\001b\006prot"
                    + "o3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
                descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_linktracker_grpc_Empty_descriptor = getDescriptor().getMessageType(0);
        internal_static_linktracker_grpc_Empty_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_Empty_descriptor, new java.lang.String[] {});
        internal_static_linktracker_grpc_RegisterChatRequest_descriptor =
                getDescriptor().getMessageType(1);
        internal_static_linktracker_grpc_RegisterChatRequest_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_RegisterChatRequest_descriptor, new java.lang.String[] {
                            "ChatId",
                        });
        internal_static_linktracker_grpc_DeleteChatRequest_descriptor =
                getDescriptor().getMessageType(2);
        internal_static_linktracker_grpc_DeleteChatRequest_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_DeleteChatRequest_descriptor, new java.lang.String[] {
                            "ChatId",
                        });
        internal_static_linktracker_grpc_ListLinksRequest_descriptor =
                getDescriptor().getMessageType(3);
        internal_static_linktracker_grpc_ListLinksRequest_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_ListLinksRequest_descriptor, new java.lang.String[] {
                            "ChatId",
                        });
        internal_static_linktracker_grpc_AddLinkRequest_descriptor =
                getDescriptor().getMessageType(4);
        internal_static_linktracker_grpc_AddLinkRequest_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_AddLinkRequest_descriptor, new java.lang.String[] {
                            "ChatId", "Link", "Tags", "Filters",
                        });
        internal_static_linktracker_grpc_RemoveLinkRequest_descriptor =
                getDescriptor().getMessageType(5);
        internal_static_linktracker_grpc_RemoveLinkRequest_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_RemoveLinkRequest_descriptor, new java.lang.String[] {
                            "ChatId", "Link",
                        });
        internal_static_linktracker_grpc_LinkResponse_descriptor =
                getDescriptor().getMessageType(6);
        internal_static_linktracker_grpc_LinkResponse_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_LinkResponse_descriptor, new java.lang.String[] {
                            "Id", "Url", "Tags", "Filters",
                        });
        internal_static_linktracker_grpc_ListLinksResponse_descriptor =
                getDescriptor().getMessageType(7);
        internal_static_linktracker_grpc_ListLinksResponse_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_ListLinksResponse_descriptor, new java.lang.String[] {
                            "Links", "Size",
                        });
        internal_static_linktracker_grpc_LinkUpdateRequest_descriptor =
                getDescriptor().getMessageType(8);
        internal_static_linktracker_grpc_LinkUpdateRequest_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_linktracker_grpc_LinkUpdateRequest_descriptor, new java.lang.String[] {
                            "Id", "Url", "Description", "TgChatIds",
                        });
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
