// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

/**
 * Protobuf type {@code linktracker.grpc.ListLinksResponse}
 */
@com.google.protobuf.Generated
public final class ListLinksResponse extends com.google.protobuf.GeneratedMessage
        implements
        // @@protoc_insertion_point(message_implements:linktracker.grpc.ListLinksResponse)
        ListLinksResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 4,
                /* suffix= */ "",
                "ListLinksResponse");
    }
    // Use ListLinksResponse.newBuilder() to construct.
    private ListLinksResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private ListLinksResponse() {
        links_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_ListLinksResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_ListLinksResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        backend.academy.linktracker.grpc.ListLinksResponse.class,
                        backend.academy.linktracker.grpc.ListLinksResponse.Builder.class);
    }

    public static final int LINKS_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private java.util.List<backend.academy.linktracker.grpc.LinkResponse> links_;
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    @java.lang.Override
    public java.util.List<backend.academy.linktracker.grpc.LinkResponse> getLinksList() {
        return links_;
    }
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends backend.academy.linktracker.grpc.LinkResponseOrBuilder> getLinksOrBuilderList() {
        return links_;
    }
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    @java.lang.Override
    public int getLinksCount() {
        return links_.size();
    }
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    @java.lang.Override
    public backend.academy.linktracker.grpc.LinkResponse getLinks(int index) {
        return links_.get(index);
    }
    /**
     * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
     */
    @java.lang.Override
    public backend.academy.linktracker.grpc.LinkResponseOrBuilder getLinksOrBuilder(int index) {
        return links_.get(index);
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private int size_ = 0;
    /**
     * <code>int32 size = 2;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
        return size_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        for (int i = 0; i < links_.size(); i++) {
            output.writeMessage(1, links_.get(i));
        }
        if (size_ != 0) {
            output.writeInt32(2, size_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < links_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, links_.get(i));
        }
        if (size_ != 0) {
            size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, size_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof backend.academy.linktracker.grpc.ListLinksResponse)) {
            return super.equals(obj);
        }
        backend.academy.linktracker.grpc.ListLinksResponse other =
                (backend.academy.linktracker.grpc.ListLinksResponse) obj;

        if (!getLinksList().equals(other.getLinksList())) return false;
        if (getSize() != other.getSize()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getLinksCount() > 0) {
            hash = (37 * hash) + LINKS_FIELD_NUMBER;
            hash = (53 * hash) + getLinksList().hashCode();
        }
        hash = (37 * hash) + SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getSize();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(
            com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(
            byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(
            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse parseFrom(
            com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(backend.academy.linktracker.grpc.ListLinksResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code linktracker.grpc.ListLinksResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements
            // @@protoc_insertion_point(builder_implements:linktracker.grpc.ListLinksResponse)
            backend.academy.linktracker.grpc.ListLinksResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_ListLinksResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_ListLinksResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            backend.academy.linktracker.grpc.ListLinksResponse.class,
                            backend.academy.linktracker.grpc.ListLinksResponse.Builder.class);
        }

        // Construct using backend.academy.linktracker.grpc.ListLinksResponse.newBuilder()
        private Builder() {}

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            if (linksBuilder_ == null) {
                links_ = java.util.Collections.emptyList();
            } else {
                links_ = null;
                linksBuilder_.clear();
            }
            bitField0_ = (bitField0_ & ~0x00000001);
            size_ = 0;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_ListLinksResponse_descriptor;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.ListLinksResponse getDefaultInstanceForType() {
            return backend.academy.linktracker.grpc.ListLinksResponse.getDefaultInstance();
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.ListLinksResponse build() {
            backend.academy.linktracker.grpc.ListLinksResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.ListLinksResponse buildPartial() {
            backend.academy.linktracker.grpc.ListLinksResponse result =
                    new backend.academy.linktracker.grpc.ListLinksResponse(this);
            buildPartialRepeatedFields(result);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartialRepeatedFields(backend.academy.linktracker.grpc.ListLinksResponse result) {
            if (linksBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    links_ = java.util.Collections.unmodifiableList(links_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.links_ = links_;
            } else {
                result.links_ = linksBuilder_.build();
            }
        }

        private void buildPartial0(backend.academy.linktracker.grpc.ListLinksResponse result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.size_ = size_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof backend.academy.linktracker.grpc.ListLinksResponse) {
                return mergeFrom((backend.academy.linktracker.grpc.ListLinksResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(backend.academy.linktracker.grpc.ListLinksResponse other) {
            if (other == backend.academy.linktracker.grpc.ListLinksResponse.getDefaultInstance()) return this;
            if (linksBuilder_ == null) {
                if (!other.links_.isEmpty()) {
                    if (links_.isEmpty()) {
                        links_ = other.links_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureLinksIsMutable();
                        links_.addAll(other.links_);
                    }
                    onChanged();
                }
            } else {
                if (!other.links_.isEmpty()) {
                    if (linksBuilder_.isEmpty()) {
                        linksBuilder_.dispose();
                        linksBuilder_ = null;
                        links_ = other.links_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        linksBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                ? internalGetLinksFieldBuilder()
                                : null;
                    } else {
                        linksBuilder_.addAllMessages(other.links_);
                    }
                }
            }
            if (other.getSize() != 0) {
                setSize(other.getSize());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            backend.academy.linktracker.grpc.LinkResponse m = input.readMessage(
                                    backend.academy.linktracker.grpc.LinkResponse.parser(), extensionRegistry);
                            if (linksBuilder_ == null) {
                                ensureLinksIsMutable();
                                links_.add(m);
                            } else {
                                linksBuilder_.addMessage(m);
                            }
                            break;
                        } // case 10
                        case 16: {
                            size_ = input.readInt32();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 16
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.util.List<backend.academy.linktracker.grpc.LinkResponse> links_ =
                java.util.Collections.emptyList();

        private void ensureLinksIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                links_ = new java.util.ArrayList<backend.academy.linktracker.grpc.LinkResponse>(links_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
                        backend.academy.linktracker.grpc.LinkResponse,
                        backend.academy.linktracker.grpc.LinkResponse.Builder,
                        backend.academy.linktracker.grpc.LinkResponseOrBuilder>
                linksBuilder_;

        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public java.util.List<backend.academy.linktracker.grpc.LinkResponse> getLinksList() {
            if (linksBuilder_ == null) {
                return java.util.Collections.unmodifiableList(links_);
            } else {
                return linksBuilder_.getMessageList();
            }
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public int getLinksCount() {
            if (linksBuilder_ == null) {
                return links_.size();
            } else {
                return linksBuilder_.getCount();
            }
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public backend.academy.linktracker.grpc.LinkResponse getLinks(int index) {
            if (linksBuilder_ == null) {
                return links_.get(index);
            } else {
                return linksBuilder_.getMessage(index);
            }
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder setLinks(int index, backend.academy.linktracker.grpc.LinkResponse value) {
            if (linksBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLinksIsMutable();
                links_.set(index, value);
                onChanged();
            } else {
                linksBuilder_.setMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder setLinks(int index, backend.academy.linktracker.grpc.LinkResponse.Builder builderForValue) {
            if (linksBuilder_ == null) {
                ensureLinksIsMutable();
                links_.set(index, builderForValue.build());
                onChanged();
            } else {
                linksBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder addLinks(backend.academy.linktracker.grpc.LinkResponse value) {
            if (linksBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLinksIsMutable();
                links_.add(value);
                onChanged();
            } else {
                linksBuilder_.addMessage(value);
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder addLinks(int index, backend.academy.linktracker.grpc.LinkResponse value) {
            if (linksBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureLinksIsMutable();
                links_.add(index, value);
                onChanged();
            } else {
                linksBuilder_.addMessage(index, value);
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder addLinks(backend.academy.linktracker.grpc.LinkResponse.Builder builderForValue) {
            if (linksBuilder_ == null) {
                ensureLinksIsMutable();
                links_.add(builderForValue.build());
                onChanged();
            } else {
                linksBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder addLinks(int index, backend.academy.linktracker.grpc.LinkResponse.Builder builderForValue) {
            if (linksBuilder_ == null) {
                ensureLinksIsMutable();
                links_.add(index, builderForValue.build());
                onChanged();
            } else {
                linksBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder addAllLinks(java.lang.Iterable<? extends backend.academy.linktracker.grpc.LinkResponse> values) {
            if (linksBuilder_ == null) {
                ensureLinksIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, links_);
                onChanged();
            } else {
                linksBuilder_.addAllMessages(values);
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder clearLinks() {
            if (linksBuilder_ == null) {
                links_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                linksBuilder_.clear();
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public Builder removeLinks(int index) {
            if (linksBuilder_ == null) {
                ensureLinksIsMutable();
                links_.remove(index);
                onChanged();
            } else {
                linksBuilder_.remove(index);
            }
            return this;
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public backend.academy.linktracker.grpc.LinkResponse.Builder getLinksBuilder(int index) {
            return internalGetLinksFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public backend.academy.linktracker.grpc.LinkResponseOrBuilder getLinksOrBuilder(int index) {
            if (linksBuilder_ == null) {
                return links_.get(index);
            } else {
                return linksBuilder_.getMessageOrBuilder(index);
            }
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public java.util.List<? extends backend.academy.linktracker.grpc.LinkResponseOrBuilder>
                getLinksOrBuilderList() {
            if (linksBuilder_ != null) {
                return linksBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(links_);
            }
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public backend.academy.linktracker.grpc.LinkResponse.Builder addLinksBuilder() {
            return internalGetLinksFieldBuilder()
                    .addBuilder(backend.academy.linktracker.grpc.LinkResponse.getDefaultInstance());
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public backend.academy.linktracker.grpc.LinkResponse.Builder addLinksBuilder(int index) {
            return internalGetLinksFieldBuilder()
                    .addBuilder(index, backend.academy.linktracker.grpc.LinkResponse.getDefaultInstance());
        }
        /**
         * <code>repeated .linktracker.grpc.LinkResponse links = 1;</code>
         */
        public java.util.List<backend.academy.linktracker.grpc.LinkResponse.Builder> getLinksBuilderList() {
            return internalGetLinksFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilder<
                        backend.academy.linktracker.grpc.LinkResponse,
                        backend.academy.linktracker.grpc.LinkResponse.Builder,
                        backend.academy.linktracker.grpc.LinkResponseOrBuilder>
                internalGetLinksFieldBuilder() {
            if (linksBuilder_ == null) {
                linksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                        backend.academy.linktracker.grpc.LinkResponse,
                        backend.academy.linktracker.grpc.LinkResponse.Builder,
                        backend.academy.linktracker.grpc.LinkResponseOrBuilder>(
                        links_, ((bitField0_ & 0x00000001) != 0), getParentForChildren(), isClean());
                links_ = null;
            }
            return linksBuilder_;
        }

        private int size_;
        /**
         * <code>int32 size = 2;</code>
         * @return The size.
         */
        @java.lang.Override
        public int getSize() {
            return size_;
        }
        /**
         * <code>int32 size = 2;</code>
         * @param value The size to set.
         * @return This builder for chaining.
         */
        public Builder setSize(int value) {

            size_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }
        /**
         * <code>int32 size = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearSize() {
            bitField0_ = (bitField0_ & ~0x00000002);
            size_ = 0;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:linktracker.grpc.ListLinksResponse)
    }

    // @@protoc_insertion_point(class_scope:linktracker.grpc.ListLinksResponse)
    private static final backend.academy.linktracker.grpc.ListLinksResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new backend.academy.linktracker.grpc.ListLinksResponse();
    }

    public static backend.academy.linktracker.grpc.ListLinksResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListLinksResponse> PARSER =
            new com.google.protobuf.AbstractParser<ListLinksResponse>() {
                @java.lang.Override
                public ListLinksResponse parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

    public static com.google.protobuf.Parser<ListLinksResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListLinksResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public backend.academy.linktracker.grpc.ListLinksResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
