// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

@com.google.protobuf.Generated
public interface ProcessingFailureReportRequestOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:linktracker.grpc.ProcessingFailureReportRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string description = 1;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 1;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString getDescriptionBytes();

    /**
     * <code>repeated int64 tg_chat_ids = 2;</code>
     * @return A list containing the tgChatIds.
     */
    java.util.List<java.lang.Long> getTgChatIdsList();
    /**
     * <code>repeated int64 tg_chat_ids = 2;</code>
     * @return The count of tgChatIds.
     */
    int getTgChatIdsCount();
    /**
     * <code>repeated int64 tg_chat_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The tgChatIds at the given index.
     */
    long getTgChatIds(int index);
}
