// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: link_tracker.proto
// Protobuf Java Version: 4.33.4

package backend.academy.linktracker.grpc;

/**
 * Protobuf type {@code linktracker.grpc.RegisterChatRequest}
 */
@com.google.protobuf.Generated
public final class RegisterChatRequest extends com.google.protobuf.GeneratedMessage
        implements
        // @@protoc_insertion_point(message_implements:linktracker.grpc.RegisterChatRequest)
        RegisterChatRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 33,
                /* patch= */ 4,
                /* suffix= */ "",
                "RegisterChatRequest");
    }
    // Use RegisterChatRequest.newBuilder() to construct.
    private RegisterChatRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private RegisterChatRequest() {}

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_RegisterChatRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
        return backend.academy.linktracker.grpc.LinkTrackerProto
                .internal_static_linktracker_grpc_RegisterChatRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        backend.academy.linktracker.grpc.RegisterChatRequest.class,
                        backend.academy.linktracker.grpc.RegisterChatRequest.Builder.class);
    }

    public static final int CHAT_ID_FIELD_NUMBER = 1;
    private long chatId_ = 0L;
    /**
     * <code>int64 chat_id = 1;</code>
     * @return The chatId.
     */
    @java.lang.Override
    public long getChatId() {
        return chatId_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (chatId_ != 0L) {
            output.writeInt64(1, chatId_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (chatId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, chatId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof backend.academy.linktracker.grpc.RegisterChatRequest)) {
            return super.equals(obj);
        }
        backend.academy.linktracker.grpc.RegisterChatRequest other =
                (backend.academy.linktracker.grpc.RegisterChatRequest) obj;

        if (getChatId() != other.getChatId()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CHAT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getChatId());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(
            com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(
            byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(
            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest parseFrom(
            com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(backend.academy.linktracker.grpc.RegisterChatRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     * Protobuf type {@code linktracker.grpc.RegisterChatRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements
            // @@protoc_insertion_point(builder_implements:linktracker.grpc.RegisterChatRequest)
            backend.academy.linktracker.grpc.RegisterChatRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_RegisterChatRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_RegisterChatRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            backend.academy.linktracker.grpc.RegisterChatRequest.class,
                            backend.academy.linktracker.grpc.RegisterChatRequest.Builder.class);
        }

        // Construct using backend.academy.linktracker.grpc.RegisterChatRequest.newBuilder()
        private Builder() {}

        private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            chatId_ = 0L;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return backend.academy.linktracker.grpc.LinkTrackerProto
                    .internal_static_linktracker_grpc_RegisterChatRequest_descriptor;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.RegisterChatRequest getDefaultInstanceForType() {
            return backend.academy.linktracker.grpc.RegisterChatRequest.getDefaultInstance();
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.RegisterChatRequest build() {
            backend.academy.linktracker.grpc.RegisterChatRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public backend.academy.linktracker.grpc.RegisterChatRequest buildPartial() {
            backend.academy.linktracker.grpc.RegisterChatRequest result =
                    new backend.academy.linktracker.grpc.RegisterChatRequest(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(backend.academy.linktracker.grpc.RegisterChatRequest result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.chatId_ = chatId_;
            }
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof backend.academy.linktracker.grpc.RegisterChatRequest) {
                return mergeFrom((backend.academy.linktracker.grpc.RegisterChatRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(backend.academy.linktracker.grpc.RegisterChatRequest other) {
            if (other == backend.academy.linktracker.grpc.RegisterChatRequest.getDefaultInstance()) return this;
            if (other.getChatId() != 0L) {
                setChatId(other.getChatId());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            chatId_ = input.readInt64();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 8
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private long chatId_;
        /**
         * <code>int64 chat_id = 1;</code>
         * @return The chatId.
         */
        @java.lang.Override
        public long getChatId() {
            return chatId_;
        }
        /**
         * <code>int64 chat_id = 1;</code>
         * @param value The chatId to set.
         * @return This builder for chaining.
         */
        public Builder setChatId(long value) {

            chatId_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }
        /**
         * <code>int64 chat_id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearChatId() {
            bitField0_ = (bitField0_ & ~0x00000001);
            chatId_ = 0L;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:linktracker.grpc.RegisterChatRequest)
    }

    // @@protoc_insertion_point(class_scope:linktracker.grpc.RegisterChatRequest)
    private static final backend.academy.linktracker.grpc.RegisterChatRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new backend.academy.linktracker.grpc.RegisterChatRequest();
    }

    public static backend.academy.linktracker.grpc.RegisterChatRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisterChatRequest> PARSER =
            new com.google.protobuf.AbstractParser<RegisterChatRequest>() {
                @java.lang.Override
                public RegisterChatRequest parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    Builder builder = newBuilder();
                    try {
                        builder.mergeFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        throw e.setUnfinishedMessage(builder.buildPartial());
                    } catch (com.google.protobuf.UninitializedMessageException e) {
                        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                    } catch (java.io.IOException e) {
                        throw new com.google.protobuf.InvalidProtocolBufferException(e)
                                .setUnfinishedMessage(builder.buildPartial());
                    }
                    return builder.buildPartial();
                }
            };

    public static com.google.protobuf.Parser<RegisterChatRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisterChatRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public backend.academy.linktracker.grpc.RegisterChatRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
